MODEL:
  WEIGHTS: "/path/to/resnet50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    STRIDE_IN_1X1: False
INPUT:
  FORMAT: "RGB"
WANDB:
  ENTITY: "landskape"
  PROJECT: "examples"